[package]
name = "soulfire"
version = "1.0.1"
description = "Frontend client for SoulFire."
authors = ["Pistonmaster"]
license = "GPL-3.0"
repository = "https://github.com/AlexProgrammerDE/SoulFireClient"
default-run = "soulfire"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.1", features = [ "updater", "fs-all", "path-all", "process-all", "system-tray", "window-all", "shell-all", "os-all", "dialog-all", "clipboard-all"] }
reqwest = { version = "0.12.4", features = ["json"] }
tar = "0.4.40"
flate2 = "1.0.30"
strip-ansi-escapes = "0.2.0"
zip = "2.1.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
