name: 'publish'

on:
  workflow_dispatch:
    inputs:
      app-version:
        description: 'Version to release'
        required: true
      server-version:
        description: 'Server version to use for release'
        required: true

jobs:
  set-server-version:
    uses: AlexProgrammerDE/SoulFireClient/.github/workflows/set-server-version.yml@main
    with:
      version: ${{ inputs.server-version }}
    secrets: inherit

  set-version:
    needs: set-server-version
    uses: AlexProgrammerDE/SoulFireClient/.github/workflows/set-version.yml@main
    with:
      version: ${{ inputs.app-version }}
    secrets: inherit

  push-release-branch:
    needs: set-version
    name: Push Release Branch

    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Push to release branch'
        uses: ad-m/github-push-action@master
        with:
          branch: 'release'

  build-tauri:
    needs: set-version
    name: Build ${{ matrix.name }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-15'
            args: '--target aarch64-apple-darwin'
            target-path: '/aarch64-apple-darwin'
            name: 'macOS 15 (AARCH64)'
            rust-targets: 'aarch64-apple-darwin'
            type: 'macos-aarch64'
          - platform: 'macos-13'
            args: '--target x86_64-apple-darwin'
            target-path: '/x86_64-apple-darwin'
            name: 'macOS 13 (AMD64)'
            rust-targets: 'x86_64-apple-darwin'
            type: 'macos-amd64'
          - platform: 'ubuntu-22.04'
            args: ''
            target-path: ''
            name: 'Ubuntu 22.04'
            rust-targets: ''
            type: 'linux'
          - platform: 'windows-2025'
            args: ''
            target-path: ''
            name: 'Windows Server 2025'
            rust-targets: ''
            type: 'windows'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: 'Shared: Checkout Repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Shared: Set up nasm'
        uses: ilammy/setup-nasm@v1

      - name: 'Shared: Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 'Shared: Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 'Shared: Install Rust toolchain'
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.rust-targets }}

      - name: 'Desktop: Cache dependencies'
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.type }}
          workspaces: src-tauri
          cache-on-failure: true
          cache-all-crates: true

      - name: 'Ubuntu: Install dependencies'
        if: matrix.type == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf jq

      - name: 'Shared: Install frontend dependencies'
        run: pnpm install

      - name: 'Desktop: Build tauri project'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          includeDebug: false
          includeRelease: true
          args: ${{ matrix.args }}

      - name: 'Desktop: Create output dir'
        shell: bash
        run: |
          mkdir artifact-output

      - name: 'Desktop: Put linux files in artifact-output'
        if: matrix.type == 'linux'
        shell: bash
        run: |
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/appimage/*.AppImage ./artifact-output/
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/appimage/*.AppImage.sig ./artifact-output/
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/deb/*.deb ./artifact-output/

      - name: 'Desktop: Put macos files in artifact-output'
        if: matrix.type == 'macos-amd64' || matrix.type == 'macos-aarch64'
        shell: bash
        run: |
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/dmg/*.dmg ./artifact-output/
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/macos/*.app.tar.gz ./artifact-output/
          mv ./src-tauri/target${{ matrix.target-path }}/release/bundle/macos/*.app.tar.gz.sig ./artifact-output/

      - name: 'Windows: Upload unsigned artifact'
        id: upload-unsigned-artifact
        if: matrix.type == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-unsigned
          path: |
            ./src-tauri/target${{ matrix.target-path }}/release/bundle/nsis/*.exe
          if-no-files-found: error

      - name: 'Windows: Notify Admin'
        if: matrix.type == 'windows'
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.ADMIN_WEBHOOK_URL }}
          content: <@864603174899941376> Permit the signing request for SoulFireClient ${{ inputs.app-version }} https://app.signpath.io/Web/e091b552-3623-4d9d-83d7-059d8f32978b/SigningRequests

      - name: 'Windows: Submit signing request'
        if: matrix.type == 'windows'
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'e091b552-3623-4d9d-83d7-059d8f32978b'
          project-slug: 'SoulFireClient'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: '/artifact-output'

      - name: 'Windows: Prepare signed artifact'
        if: matrix.platform == 'windows-2025'
        shell: bash
        run: |
          fileName=$(ls artifact-output/*.exe)
          pnpm tauri signer sign -k "${{ secrets.TAURI_PRIVATE_KEY }}" -p "${{ secrets.TAURI_KEY_PASSWORD }}" $fileName

      - name: 'Desktop: Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}
          path: |
            ./artifact-output/*
          if-no-files-found: error

  publish-release:
    needs: build-tauri
    name: Publish Release

    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - name: Download linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: release-artifacts/linux
      - name: Download macos-aarch64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64
          path: release-artifacts/macos-aarch64
      - name: Download macos-amd64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-amd64
          path: release-artifacts/macos-amd64
      - name: Download windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: release-artifacts/windows
      - name: Create latest.json
        run: |
          linuxAppImageFile=$(ls release-artifacts/linux/*.AppImage)
          linuxAppImageSigFile=$(ls release-artifacts/linux/*.AppImage.sig)
          macosAarch64File=$(ls release-artifacts/macos-aarch64/*.app.tar.gz)
          macosAarch64SigFile=$(ls release-artifacts/macos-aarch64/*.app.tar.gz.sig)
          macosAmd64File=$(ls release-artifacts/macos-amd64/*.app.tar.gz)
          macosAmd64SigFile=$(ls release-artifacts/macos-amd64/*.app.tar.gz.sig)
          windowsFile=$(ls release-artifacts/windows/*.exe)
          windowsSigFile=$(ls release-artifacts/windows/*.exe.sig)
          currentDate=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
          cat << EOF > 'release-artifacts/latest.json'
          {
            "version": "${{ inputs.app-version }}",
            "notes": "See the assets to download this version and install.",
            "pub_date": "${currentDate}",
            "platforms": {
              "windows-x86_64": {
                "signature": "$(cat $windowsSigFile)",
                "url": "https://github.com/AlexProgrammerDE/SoulFireClient/releases/download/${{ inputs.app-version }}/$(basename $windowsFile)"
              },
              "darwin-aarch64": {
                "signature": "$(cat $macosAarch64SigFile)",
                "url": "https://github.com/AlexProgrammerDE/SoulFireClient/releases/download/${{ inputs.app-version }}/$(basename $macosAarch64File)"
              },
              "darwin-x86_64": {
                "signature": "$(cat macOSAmd64SigFile)",
                "url": "https://github.com/AlexProgrammerDE/SoulFireClient/releases/download/${{ inputs.app-version }}/$(macOSAmd64File)"
              },
              "linux-x86_64": {
                "signature": "$(cat $linuxAppImageSigFile)",
                "url": "https://github.com/AlexProgrammerDE/SoulFireClient/releases/download/${{ inputs.app-version }}/$(linuxAppImageFile)"
              }
            }
          }
          EOF

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: COMMIT
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## Feature",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## Fix",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## Performance",
                    "labels": ["perf"]
                },
                {
                    "title": "## Refactor",
                    "labels": ["refactor"]
                },
                {
                    "title": "## Documentation",
                    "labels": ["docs"]
                },
                {
                    "title": "## Build",
                    "labels": ["build", "chore", "ci"]
                },
                {
                    "title": "## Style",
                    "labels": ["style"]
                },
                {
                    "title": "## Test",
                    "labels": ["test"]
                },
                {
                    "title": "## Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: init-release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          tag_name: ${{ steps.get-version.outputs.package-version }}
          generate_release_notes: false
          target_commitish: main
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SoulFireClient ${{ steps.get-version.outputs.package-version }}
          files: |
            release-artifacts/**/*.exe
            release-artifacts/**/*.AppImage
            release-artifacts/**/*.deb
            release-artifacts/**/*.app.tar.gz
            release-artifacts/**/*.dmg
            release-artifacts/latest.json

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: <@&850705047938793503> New SoulFireClient version released!
          embed-title: SoulFireClient ${{ inputs.app-version }}
          embed-description: SoulFireClient ${{ inputs.app-version }} has been released! Changelog and download can be found at https://github.com/AlexProgrammerDE/SoulFireClient/releases/tag/${{ inputs.app-version }}
          embed-color: 3312063
          embed-thumbnail-url: https://soulfiremc.com/logo.png
