name: 'publish'

on:
  workflow_dispatch:
    inputs:
      app-version:
        description: 'Version to release'
        required: true
      server-version:
        description: 'Server version to use for release'
        required: true

jobs:
  set-server-version:
    uses: AlexProgrammerDE/PistonPanel/.github/workflows/set-server-version.yml@main
    with:
      version: ${{ inputs.server-version }}
    secrets: inherit

  set-version:
    needs: set-server-version
    uses: AlexProgrammerDE/PistonPanel/.github/workflows/set-version.yml@main
    with:
      version: ${{ inputs.app-version }}
    secrets: inherit

  build:
    needs: set-version
    name: Build and Test
    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: 'Install pnpm packages'
        run: |
          pnpm install --prefer-offline --frozen-lockfile

      - name: 'Build pnpm packages'
        run: |
          pnpm build

  publish-release:
    needs: build
    name: Publish Release

    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: COMMIT
          toTag: ${{ github.ref }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "commit_template": "- [`#{{SHORT_MERGE_SHA}}`](https://github.com/AlexProgrammerDE/PistonPanel/commit/#{{MERGE_SHA}}) #{{TITLE}}",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## 🏎️ Performance",
                    "labels": ["perf"]
                },
                {
                    "title": "## 🏗 Refactor",
                    "labels": ["refactor"]
                },
                {
                    "title": "## 📝 Documentation",
                    "labels": ["docs"]
                },
                {
                    "title": "## 🔨 Build",
                    "labels": ["build", "chore", "ci"]
                },
                {
                    "title": "## 💅 Style",
                    "labels": ["style"]
                },
                {
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## 💬 Other",
                    "labels": []
                },
                {
                  "title": "## 📦 Dependencies",
                  "labels": ["dependencies"]
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ],
              "custom_placeholders": [
                {
                  "name": "SHORT_MERGE_SHA",
                  "source": "MERGE_SHA",
                  "transformer": {
                    "pattern": "^([0-9a-f]{7})[0-9a-f]*$",
                    "target": "$1"
                  }
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: init-release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ steps.github_release.outputs.changelog }}
          tag_name: ${{ inputs.app-version }}
          generate_release_notes: false
          target_commitish: main
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PistonPanel ${{ inputs.app-version }}

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: <@&850705047938793503> New PistonPanel version released!
          embed-title: PistonPanel ${{ inputs.app-version }}
          embed-description: PistonPanel ${{ inputs.app-version }} has been released! Changelog and download can be found at https://github.com/AlexProgrammerDE/PistonPanel/releases/tag/${{ inputs.app-version }}
          embed-color: 3312063
          embed-thumbnail-url: https://pistonpanel.com/logo.png
