name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            name: 'macos-aarch64'
            rust-targets: 'aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            name: 'macos-x86_64'
            rust-targets: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            name: 'linux'
            rust-targets: ''
          - platform: 'windows-latest'
            args: '--config src-tauri/tauri.preview.conf.json'
            name: 'windows'
            rust-targets: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: 'Shared: Checkout'
        uses: actions/checkout@v4

      - name: 'Shared: Set up nasm'
        uses: ilammy/setup-nasm@v1

      - name: 'Shared: Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 'Shared: Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 'Shared: Install Rust toolchain'
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.rust-targets }}

      - name: 'Desktop: Cache dependencies'
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.name }}
          workspaces: src-tauri
          cache-on-failure: true
          cache-all-crates: true

      - name: 'Ubuntu: Install dependencies'
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 'Shared: Install frontend dependencies'
        run: pnpm install

      - name: 'Windows: Install SignPath command'
        if: matrix.name == 'windows'
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -scope CurrentUser -Force -Name SignPath

      - name: 'Desktop: Build tauri project'
        uses: tauri-apps/tauri-action@v0
        env:
          SIGNPATH_POLICY_SLUG: release-signing
          SIGNPATH_API_KEY: ${{ secrets.SIGNPATH_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: __VERSION__
          releaseName: 'SoulFireClient __VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          includeDebug: false
          includeRelease: true
          args: ${{ matrix.args }}
